//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commune
    {
        public int commune_id { get; set; }
        public string commune_name { get; set; }
        public Nullable<int> district_id { get; set; }
    
        public virtual District District { get; set; }
    }
}
